### ISSUE TITLE
Error "[-] Could not resolve PTs" when running on Ubuntu 18.04

### ISSUE THREAD

**Issue by liuyibox** [misc0110/PTEditor#18]
OS: Ubuntu 18.04.5 LTS
Processor: Intel® Core™ i7-10700 CPU @ 2.90GHz × 16 , x86_64
Kernel: 5.4.0-72-generic

I'm trying to run the compiled example executable after modifying the definition of **PTEDITOR_DEVICE_PATH** in **/module/pteditor.h** as shown below:
> 18 #define PTEDITOR_DEVICE_NAME "pteditor.mod"                                                      
> 19 #define PTEDITOR_DEVICE_PATH "/usr/src/pteditor-0.4.2/" PTEDITOR_DEVICE_NAME 

However it gives the error:
> [-] Could not resolve PTs

I am wondering what should **PTEDITOR_DEVICE_PATH** be? In the source code, it directs to "/dev/pteditor". However, after following installation guidance, I have no file called "pteditor" under the "/dev/" path in my ubuntu. That's why I have to modify the path as quoted above. Reading "pteditor" file can only work in this way and "/usr/src/pteditor-0.4.2/" is the only place where I can find pteditor-related files. It seems that I missed some files during installation. Am I right? 

Any ideas of what did I do wrong? Any hints would be appreciated.

**Comment by misc0110** [comment]
The `PTEDITOR_DEVICE_PATH` should not be changed, it has to be `/dev/pteditor`. This pseudo-file is the interface to the kernel module and is automatically created when loading the kernel module. If you installed the kernel module via the PPA, you only have to execute `sudo modprobe pteditor` to load the kernel module. In case you compiled it yourself, execute `sudo insmod module/pteditor.ko` to load the module.
