### ISSUE TITLE
Request for pteditor package pointer

### ISSUE THREAD

**Issue by liuyibox** [misc0110/PTEditor#19]
It looks like the real implementations of ptedit_resolve_kernel and ptedit_update_kernel are in the pteditor driver module, which is loaded before these API calls. I am wondering if there are sources we could learn deeper on how pteditor implements the detailed functionalities.

**Comment by misc0110** [comment]
Correct. You can simply look at the source code of the module. For Linux, the relevant code starts at https://github.com/misc0110/PTEditor/blob/14c2db44e7e61a48059fca7a015a94c1a11531a2/module/pteditor.c#L439 (resolve) and https://github.com/misc0110/PTEditor/blob/14c2db44e7e61a48059fca7a015a94c1a11531a2/module/pteditor.c#L450 (update).
