### ISSUE TITLE
error: assigning to 'size_t' (aka 'unsigned long') from incompatible type 'pgd_t'

### ISSUE THREAD

**Issue by xingxinggu** [misc0110/PTEditor#30]
error: assigning to 'size_t' (aka 'unsigned long') from incompatible type 'pgd_t'
if(vm->p4d) user->p4d = (vm->p4d)->pgd;

**Comment by xingxinggu** [comment]
based on linux kernel 5.10

**Comment by misc0110** [comment]
Which GCC version are you using?
