### ISSUE TITLE
Is PTEditor thread safe?

### ISSUE THREAD

**Issue by FLAYhhh** [misc0110/PTEditor#38]
I mean, when modifying page tables such as mapping/unmapping pages in user space.

**Comment by misc0110** [comment]
By default, no. 

Theoretically, you can use the `PTEDITOR_IOCTL_CMD_VM_LOCK` and `PTEDITOR_IOCTL_CMD_VM_UNLOCK` ioctl:https://github.com/misc0110/PTEditor/blob/b6338d4d7ae0bc8cd8f61be4dd9ac02fc9e0630d/module/pteditor.c#L476
These ioctls lock/unlock the kernel structures while modifying them. However, this is entirely untested. If you decide to use it and find bugs there, I'd be happy to take pull requests.

**Comment by FLAYhhh** [comment]
thanks, I will play with them.
