### ISSUE TITLE
PTEditor  init failure in two process

### ISSUE THREAD

**Issue by CupidLiuTian** [misc0110/PTEditor#39]
I have two prcocess, all of them will  call pteditor_init,  just one of them can success, the other will failure with the following logs:
[-]Error: Could not open PTEditor device: /dev/pteditor
[-] Could not initialize ptedit (did you load the kernel module?)

How can i  use PTEditor in two process?

**Comment by misc0110** [comment]
Currently, there is a check to prevent it from being used in multiple processes at the same time: https://github.com/misc0110/PTEditor/blob/b6338d4d7ae0bc8cd8f61be4dd9ac02fc9e0630d/module/pteditor.c#L139-L141

You can (at your own risk) remove this check, then you can use it in multiple processes at the same time. However, this is entirely untested.

**Comment by CupidLiuTian** [comment]
Ok, I get it. 
Thanks for your reply.
